<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.189">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Hedavam Solano">
<meta name="dcterms.date" content="2023-04-19">
<meta name="description" content="Examining sex-based algorithmic bias using an income classifiction model.">

<title>My CSCI 0451 Blog - Auditing Allocative Bias</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<style>
    .quarto-title-block .quarto-title-banner {
      color: white;
background-image: url(../../img/landscape.png);
background-size: cover;
    }
    </style>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">My CSCI 0451 Blog</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html">About</a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Auditing Allocative Bias</h1>
                  <div>
        <div class="description">
          Examining sex-based algorithmic bias using an income classifiction model.
        </div>
      </div>
                </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Hedavam Solano </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">April 19, 2023</p>
      </div>
    </div>
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<div class="cell" data-tags="[]" data-execution_count="141">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> matplotlib <span class="im">import</span> pyplot <span class="im">as</span> plt</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="overview" class="level1">
<h1>Overview</h1>
<section id="goal" class="level2">
<h2 class="anchored" data-anchor-id="goal">Goal</h2>
<p>Creat a machine learning model that predicts if someone’s income is over $50K on the basis of sex. Then, we’ll perform a fairness audit to assess if our algorithm has a gender bias.</p>
</section>
<section id="approach" class="level2">
<h2 class="anchored" data-anchor-id="approach">Approach</h2>
<ul>
<li>Choose Problem
<ul>
<li>Import appropriate dataset for training</li>
<li>Chosse Features</li>
</ul></li>
<li>Basic Descriptives + visuals (if I’m not lazy)</li>
<li>Model Training &amp; Tuning</li>
<li>Model Auditing</li>
<li>Concluding Discussion</li>
</ul>
<p>Useful Resources: - https://middlebury-csci-0451.github.io/CSCI-0451/lecture-notes/classification-in-practice.html</p>
</section>
</section>
<section id="choose-problem-prepare-data-for-modeling" class="level1">
<h1>Choose Problem + Prepare Data For Modeling</h1>
<p>Our Problem: Predict whether income is over $50K on the basis of demographics excluding sex, and audit for gender bias. The modeling is based on data from respondents in the state of Florida in 2018.</p>
<section id="import-appropriate-dataset-for-training" class="level2">
<h2 class="anchored" data-anchor-id="import-appropriate-dataset-for-training">Import appropriate dataset for training</h2>
<div class="cell" data-execution_count="142">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> folktables <span class="im">import</span> ACSDataSource, ACSEmploymalet, BasicProblem, adult_filter</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>STATE <span class="op">=</span> <span class="st">"FL"</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>data_source <span class="op">=</span> ACSDataSource(survey_year<span class="op">=</span><span class="st">'2018'</span>, </span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>                            horizon<span class="op">=</span><span class="st">'1-Year'</span>, </span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>                            survey<span class="op">=</span><span class="st">'person'</span>)</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>acs_data <span class="op">=</span> data_source.get_data(states<span class="op">=</span>[STATE], download<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>acs_data.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="142">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>RT</th>
      <th>SERIALNO</th>
      <th>DIVISION</th>
      <th>SPORDER</th>
      <th>PUMA</th>
      <th>REGION</th>
      <th>ST</th>
      <th>ADJINC</th>
      <th>PWGTP</th>
      <th>AGEP</th>
      <th>...</th>
      <th>PWGTP71</th>
      <th>PWGTP72</th>
      <th>PWGTP73</th>
      <th>PWGTP74</th>
      <th>PWGTP75</th>
      <th>PWGTP76</th>
      <th>PWGTP77</th>
      <th>PWGTP78</th>
      <th>PWGTP79</th>
      <th>PWGTP80</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>P</td>
      <td>2018GQ0000011</td>
      <td>5</td>
      <td>1</td>
      <td>12702</td>
      <td>3</td>
      <td>12</td>
      <td>1013097</td>
      <td>9</td>
      <td>64</td>
      <td>...</td>
      <td>8</td>
      <td>2</td>
      <td>15</td>
      <td>9</td>
      <td>7</td>
      <td>8</td>
      <td>0</td>
      <td>14</td>
      <td>8</td>
      <td>15</td>
    </tr>
    <tr>
      <th>1</th>
      <td>P</td>
      <td>2018GQ0000056</td>
      <td>5</td>
      <td>1</td>
      <td>9907</td>
      <td>3</td>
      <td>12</td>
      <td>1013097</td>
      <td>53</td>
      <td>95</td>
      <td>...</td>
      <td>53</td>
      <td>52</td>
      <td>53</td>
      <td>4</td>
      <td>98</td>
      <td>3</td>
      <td>52</td>
      <td>102</td>
      <td>100</td>
      <td>102</td>
    </tr>
    <tr>
      <th>2</th>
      <td>P</td>
      <td>2018GQ0000085</td>
      <td>5</td>
      <td>1</td>
      <td>7102</td>
      <td>3</td>
      <td>12</td>
      <td>1013097</td>
      <td>26</td>
      <td>15</td>
      <td>...</td>
      <td>22</td>
      <td>4</td>
      <td>28</td>
      <td>45</td>
      <td>50</td>
      <td>51</td>
      <td>23</td>
      <td>23</td>
      <td>27</td>
      <td>3</td>
    </tr>
    <tr>
      <th>3</th>
      <td>P</td>
      <td>2018GQ0000092</td>
      <td>5</td>
      <td>1</td>
      <td>3302</td>
      <td>3</td>
      <td>12</td>
      <td>1013097</td>
      <td>80</td>
      <td>20</td>
      <td>...</td>
      <td>79</td>
      <td>136</td>
      <td>145</td>
      <td>12</td>
      <td>84</td>
      <td>12</td>
      <td>80</td>
      <td>79</td>
      <td>14</td>
      <td>74</td>
    </tr>
    <tr>
      <th>4</th>
      <td>P</td>
      <td>2018GQ0000104</td>
      <td>5</td>
      <td>1</td>
      <td>10501</td>
      <td>3</td>
      <td>12</td>
      <td>1013097</td>
      <td>31</td>
      <td>18</td>
      <td>...</td>
      <td>5</td>
      <td>4</td>
      <td>5</td>
      <td>31</td>
      <td>29</td>
      <td>5</td>
      <td>5</td>
      <td>31</td>
      <td>4</td>
      <td>3</td>
    </tr>
  </tbody>
</table>
<p>5 rows × 286 columns</p>
</div>
</div>
</div>
</section>
<section id="choose-features" class="level2">
<h2 class="anchored" data-anchor-id="choose-features">Choose Features</h2>
<div class="cell" data-execution_count="143">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>possible_features<span class="op">=</span>[<span class="st">'AGEP'</span>, <span class="st">'COW'</span>, <span class="st">'SCHL'</span>, <span class="st">'MAR'</span>, <span class="st">'OCCP'</span>, <span class="st">'POBP'</span>, <span class="st">'RELP'</span>, <span class="st">'WKHP'</span>, <span class="st">'RAC1P'</span>, <span class="st">'SEX'</span>, <span class="st">'PINCP'</span>] <span class="co">#10 FEATURES FOR ACSIncome as listed in paper + PINCP as Target</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>acs_data[possible_features].head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="143">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>AGEP</th>
      <th>COW</th>
      <th>SCHL</th>
      <th>MAR</th>
      <th>OCCP</th>
      <th>POBP</th>
      <th>RELP</th>
      <th>WKHP</th>
      <th>RAC1P</th>
      <th>SEX</th>
      <th>PINCP</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>64</td>
      <td>NaN</td>
      <td>16.0</td>
      <td>1</td>
      <td>NaN</td>
      <td>327</td>
      <td>16</td>
      <td>NaN</td>
      <td>8</td>
      <td>1</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>1</th>
      <td>95</td>
      <td>NaN</td>
      <td>16.0</td>
      <td>2</td>
      <td>NaN</td>
      <td>12</td>
      <td>16</td>
      <td>NaN</td>
      <td>1</td>
      <td>2</td>
      <td>14500.0</td>
    </tr>
    <tr>
      <th>2</th>
      <td>15</td>
      <td>NaN</td>
      <td>12.0</td>
      <td>5</td>
      <td>NaN</td>
      <td>12</td>
      <td>16</td>
      <td>NaN</td>
      <td>2</td>
      <td>1</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>3</th>
      <td>20</td>
      <td>1.0</td>
      <td>16.0</td>
      <td>5</td>
      <td>5240.0</td>
      <td>11</td>
      <td>17</td>
      <td>40.0</td>
      <td>9</td>
      <td>1</td>
      <td>4900.0</td>
    </tr>
    <tr>
      <th>4</th>
      <td>18</td>
      <td>NaN</td>
      <td>16.0</td>
      <td>5</td>
      <td>NaN</td>
      <td>40</td>
      <td>17</td>
      <td>NaN</td>
      <td>2</td>
      <td>1</td>
      <td>0.0</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<div class="cell" data-execution_count="144">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co">#take out sex (feature we're auditing bias for) and total person’s income (target)</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>features_to_use <span class="op">=</span> [f <span class="cf">for</span> f <span class="kw">in</span> possible_features <span class="cf">if</span> f <span class="kw">not</span> <span class="kw">in</span> [<span class="st">"PINCP"</span>, <span class="st">"SEX"</span>]]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="145">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>IncomeProblem <span class="op">=</span> BasicProblem(</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    features<span class="op">=</span>features_to_use,</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    target<span class="op">=</span><span class="st">'PINCP'</span>,</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    target_transform<span class="op">=</span><span class="kw">lambda</span> x: x <span class="op">&gt;</span> <span class="dv">50000</span>, <span class="co">#0 if PINCP &lt;=50k; #1 if PINCP &gt;50k</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    group<span class="op">=</span><span class="st">'SEX'</span>,</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    preprocess<span class="op">=</span>adult_filter,</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>    postprocess<span class="op">=</span><span class="kw">lambda</span> x: np.nan_to_num(x, <span class="op">-</span><span class="dv">1</span>),</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>features, label, group <span class="op">=</span> IncomeProblem.df_to_numpy(acs_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="146">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> train_test_split</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>X_train, X_test, y_train, y_test, group_train, group_test <span class="op">=</span> train_test_split(</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>    features, label, group, test_size<span class="op">=</span><span class="fl">0.2</span>, random_state<span class="op">=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="basic-descriptives" class="level1">
<h1>Basic Descriptives</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>Note: These basic descriptives are based only the training dataset.</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="147">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co">#create dataframe w/ training data for purposes of finding basic descriptives more easily</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.DataFrame(X_train, columns <span class="op">=</span> features_to_use)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"group"</span>] <span class="op">=</span> group_train</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"label"</span>] <span class="op">=</span> y_train</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="148">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>df.head(<span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="148">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>AGEP</th>
      <th>COW</th>
      <th>SCHL</th>
      <th>MAR</th>
      <th>OCCP</th>
      <th>POBP</th>
      <th>RELP</th>
      <th>WKHP</th>
      <th>RAC1P</th>
      <th>group</th>
      <th>label</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>64.0</td>
      <td>1.0</td>
      <td>21.0</td>
      <td>1.0</td>
      <td>9030.0</td>
      <td>39.0</td>
      <td>0.0</td>
      <td>96.0</td>
      <td>1.0</td>
      <td>1</td>
      <td>True</td>
    </tr>
    <tr>
      <th>1</th>
      <td>68.0</td>
      <td>3.0</td>
      <td>16.0</td>
      <td>3.0</td>
      <td>5400.0</td>
      <td>12.0</td>
      <td>0.0</td>
      <td>40.0</td>
      <td>2.0</td>
      <td>2</td>
      <td>False</td>
    </tr>
    <tr>
      <th>2</th>
      <td>28.0</td>
      <td>4.0</td>
      <td>20.0</td>
      <td>5.0</td>
      <td>5310.0</td>
      <td>13.0</td>
      <td>0.0</td>
      <td>20.0</td>
      <td>1.0</td>
      <td>1</td>
      <td>False</td>
    </tr>
    <tr>
      <th>3</th>
      <td>50.0</td>
      <td>1.0</td>
      <td>16.0</td>
      <td>1.0</td>
      <td>3603.0</td>
      <td>12.0</td>
      <td>0.0</td>
      <td>40.0</td>
      <td>2.0</td>
      <td>2</td>
      <td>False</td>
    </tr>
    <tr>
      <th>4</th>
      <td>26.0</td>
      <td>2.0</td>
      <td>20.0</td>
      <td>5.0</td>
      <td>5400.0</td>
      <td>48.0</td>
      <td>0.0</td>
      <td>40.0</td>
      <td>1.0</td>
      <td>2</td>
      <td>False</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<div class="cell" data-execution_count="149">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>df.shape[<span class="dv">0</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="149">
<pre><code>79140</code></pre>
</div>
</div>
<p>There are 79140 people in this training dataset</p>
<div class="cell" data-execution_count="280">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"label"</span>].value_counts(normalize <span class="op">=</span> <span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="280">
<pre><code>False    0.668815
True     0.331185
Name: label, dtype: float64</code></pre>
</div>
</div>
<p>Approximately 33% of these people have a target label corresponding to 1 (true), meaning their income is greater than $50,000.</p>
<div class="cell" data-execution_count="278">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"group"</span>].value_counts()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="278">
<pre><code>1    40684
2    38456
Name: group, dtype: int64</code></pre>
</div>
</div>
<p>There are 40,684 individuals in group 1 (male respondents) and 38,456 individuals in group 2 (female respondents)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>over50k <span class="op">=</span> df.query(<span class="st">"label == True"</span>) <span class="co">#filter out respondents that make &gt;50k</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>over50k[<span class="st">"group"</span>].value_counts()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="407">
<pre><code>1    16231
2     9979
Name: group, dtype: int64</code></pre>
</div>
</div>
<p>There are 16,231 male individuals who make more than \$50,000 in group 1 and 9,979 female individuals who make more than \$50,000 in group 2</p>
<div class="cell" data-execution_count="468">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co">#prevalence or base rates</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="dv">16231</span><span class="op">/</span><span class="dv">40684</span>)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="dv">9979</span><span class="op">/</span><span class="dv">38456</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0.3989529053190443
0.259491366756813</code></pre>
</div>
</div>
<p>Approximately 39.9% of the male respondents (group 1) have an income over \$50,000 (target label equals 1) and appproximately 25.9% of the female respondents (group 2) have an income over \$50,000 (target label equals 1).</p>
<div class="cell" data-execution_count="433">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>black_white <span class="op">=</span> df.query(<span class="st">"RAC1P == 1.0 or RAC1P == 2.0"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="434">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>grouped_over50k_black_white <span class="op">=</span> black_white.groupby([<span class="st">"group"</span>, <span class="st">"RAC1P"</span>], as_index<span class="op">=</span><span class="va">False</span>)[<span class="st">"label"</span>].value_counts(normalize <span class="op">=</span> <span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="435">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>grouped_over50k_black_white <span class="op">=</span> grouped_over50k_black_white.query(<span class="st">"label == True"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="436">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>grouped_over50k_black_white</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="436">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>group</th>
      <th>RAC1P</th>
      <th>label</th>
      <th>proportion</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>1</th>
      <td>1</td>
      <td>1.0</td>
      <td>True</td>
      <td>0.430228</td>
    </tr>
    <tr>
      <th>3</th>
      <td>1</td>
      <td>2.0</td>
      <td>True</td>
      <td>0.221417</td>
    </tr>
    <tr>
      <th>5</th>
      <td>2</td>
      <td>1.0</td>
      <td>True</td>
      <td>0.281288</td>
    </tr>
    <tr>
      <th>7</th>
      <td>2</td>
      <td>2.0</td>
      <td>True</td>
      <td>0.155718</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<div class="cell" data-execution_count="437">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>sns.set_theme(style<span class="op">=</span><span class="st">"whitegrid"</span>)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>g <span class="op">=</span> sns.catplot(</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>    data<span class="op">=</span>grouped_over50k_black_white, kind<span class="op">=</span><span class="st">"bar"</span>,</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>    x<span class="op">=</span><span class="st">"group"</span>, y<span class="op">=</span><span class="st">"proportion"</span>, hue<span class="op">=</span><span class="st">"RAC1P"</span>, legend_out <span class="op">=</span> <span class="va">True</span>)</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>g.fig.suptitle(<span class="st">'Proportion of respondants making over 50k by gender and race'</span>, fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>g.set_axis_labels(<span class="st">""</span>, <span class="st">"Proportion making over 50k"</span>)</span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>g.set_xticklabels([<span class="st">'Male'</span>, <span class="st">'Female'</span>])</span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>g._legend.set_title(<span class="st">"Race"</span>)</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>new_labels <span class="op">=</span> [<span class="st">'White'</span>, <span class="st">'Black'</span>]</span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> t, l <span class="kw">in</span> <span class="bu">zip</span>(g._legend.texts, new_labels):</span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a>    t.set_text(l)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-21-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>Based on the responses from this survey, our basic descriptives tell us:</p>
<ul>
<li>Most people’s income is less than 50k.</li>
<li>There are about as many female respondents as there is male respondents</li>
<li>A larger quantity and proportion of male respondents have an income greater than 50k as opposed to the their female counterparts</li>
<li>Intersectional Bias:
<ul>
<li>Interestingly, the proportion of white females making over \$50k is higher than the proportion of black males making over \$50k. The proportion of black females making over \$50k is the lowest for all groupings. These findings are about our dataset before modeling, meaning they represent real-world trends as captured by the American Community Survey’s Public Use Microdata Sample (ACS PUMS), which are often informed by biases. At this macro level, the disparities amongst these groups that are observed may be attributed to gender and racial biases. Though at a micro level, some analyses may be done to try to disprove these claims.</li>
<li>Do we only consider income inequality to be present if two people of different groups working the same jobs are paid differently? Or, does income inequality encompass who gets to work what types of jobs? More detailed data would be neccessary to wholly answer either of these questions. The disparities observed here may be sufficient to partially answer these questions, however, and may be indicative of the privilege white males hold that results in them usually working higher paying jobs or getting paid more for the same jobs that people in the other groups also do.</li>
</ul></li>
</ul>
<p>Useful Resources (for this section): - https://jakevdp.github.io/PythonDataScienceHandbook/03.00-introduction-to-pandas.html - https://levelup.gitconnected.com/20-pandas-functions-for-80-of-your-data-science-tasks-b610c8bfe63c</p>
</section>
<section id="model-training" class="level1">
<h1>Model Training</h1>
<p>The model we will use is the RandomForestClassifier. For more information on the specifics of this model refer to this previous blog post: <a href="https://hedavam.github.io/posts/Classifying%20Palmer%20Penguins%20-%20ML%20Workflow/#model">Classifying Palmer Penguins</a></p>
<section id="tuning-hyperparameters-with-cross-validation" class="level3">
<h3 class="anchored" data-anchor-id="tuning-hyperparameters-with-cross-validation">Tuning hyperparameters with cross-validation</h3>
<div class="cell" data-execution_count="405">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.pipeline <span class="im">import</span> make_pipeline</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.preprocessing <span class="im">import</span> StandardScaler</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.ensemble <span class="im">import</span> RandomForestClassifier</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> cross_val_score</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a><span class="co">#create model</span></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> make_pipeline(StandardScaler(), RandomForestClassifier(max_depth<span class="op">=</span><span class="dv">10</span>, random_state<span class="op">=</span><span class="dv">0</span>))</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>model.fit(X_train, y_train)</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a><span class="co">#cross-validation</span></span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>model_scores <span class="op">=</span> cross_val_score(model, X_train, y_train, cv<span class="op">=</span><span class="dv">5</span>)</span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(model_scores)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[0.80439727 0.80414455 0.80427091 0.80243872 0.80332322]</code></pre>
</div>
</div>
<p>The hyperparameter we tuned with the help of cross-validation for this RandomForestClassifier is the max_depth. Note: This could be done iteratively, but it is computationally expensive and takes a while to do. For our purposes, it’s arguably more effective to use trial and error to select the max_depth and settle on a value after we see the cross-validation scores plateauing (numbers in the 5-10 range usually work well, though the optimal selection is data dependent).</p>
</section>
</section>
<section id="model-auditing" class="level1">
<h1>Model Auditing</h1>
<section id="preliminaries" class="level3">
<h3 class="anchored" data-anchor-id="preliminaries">Preliminaries</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co">#gather predictions on test data</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>y_hat_tests <span class="op">=</span> model.predict(X_test)  </span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="co">#functions for Positive Predictive Value, False Negative Rate, False Positive Rate</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> bias_rates(cf, selection):</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>    TN <span class="op">=</span> cf[<span class="dv">0</span>,<span class="dv">0</span>] <span class="co">#Predict false, actual is false</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>    FP <span class="op">=</span> cf[<span class="dv">0</span>,<span class="dv">1</span>] <span class="co">#Predict true, actual is false</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>    FN <span class="op">=</span> cf[<span class="dv">1</span>,<span class="dv">0</span>] <span class="co">#Predict false, actual is true</span></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>    TP <span class="op">=</span> cf[<span class="dv">1</span>,<span class="dv">1</span>] <span class="co">#Predict true, actual is false</span></span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> selection <span class="op">==</span> <span class="st">"PPV"</span>:</span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span> (TP<span class="op">/</span>(TP<span class="op">+</span>FP))</span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> selection <span class="op">==</span> <span class="st">"FNR"</span>:</span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span> (FN<span class="op">/</span>(TP<span class="op">+</span>FN))</span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> selection <span class="op">==</span> <span class="st">"FPR"</span>:</span>
<span id="cb28-18"><a href="#cb28-18" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span> (FP<span class="op">/</span>(FP<span class="op">+</span>TN))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="overall-measures" class="level2">
<h2 class="anchored" data-anchor-id="overall-measures">Overall Measures</h2>
<section id="the-models-overall-accuracy-in-predicting-whether-someones-income-is-over-50000-is" class="level4">
<h4 class="anchored" data-anchor-id="the-models-overall-accuracy-in-predicting-whether-someones-income-is-over-50000-is">The model’s overall accuracy in predicting whether someone’s income is over $50,000 is:</h4>
<div class="cell" data-execution_count="389">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>(y_hat_tests <span class="op">==</span> y_test).mean()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="389">
<pre><code>0.8022744503411675</code></pre>
</div>
</div>
</section>
<section id="the-models-overall-positive-predictive-value-ppv-is" class="level4">
<h4 class="anchored" data-anchor-id="the-models-overall-positive-predictive-value-ppv-is">The model’s overall positive predictive value (PPV) is:</h4>
<div class="cell" data-execution_count="390">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>bias_rates(confusion_matrix(y_test, y_hat_tests), <span class="st">"PPV"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0.7387549478229579</code></pre>
</div>
</div>
</section>
<section id="the-models-overall-false-negative-rate-fnr-is" class="level4">
<h4 class="anchored" data-anchor-id="the-models-overall-false-negative-rate-fnr-is">The model’s overall false negative rate FNR is:</h4>
<div class="cell" data-execution_count="391">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>bias_rates(confusion_matrix(y_test, y_hat_tests), <span class="st">"FNR"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0.37465732561681386</code></pre>
</div>
</div>
</section>
<section id="the-models-overall-false-positive-rate-fpr-is" class="level4">
<h4 class="anchored" data-anchor-id="the-models-overall-false-positive-rate-fpr-is">The model’s overall false positive rate FPR is:</h4>
<div class="cell" data-execution_count="392">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>bias_rates(confusion_matrix(y_test, y_hat_tests), <span class="st">"FPR"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0.10984189424313488</code></pre>
</div>
</div>
</section>
<section id="by-group-measures" class="level3">
<h3 class="anchored" data-anchor-id="by-group-measures">By-Group Measures</h3>
</section>
<section id="for-male-individuals" class="level3">
<h3 class="anchored" data-anchor-id="for-male-individuals">For Male Individuals</h3>
<section id="the-accuracy-is" class="level4">
<h4 class="anchored" data-anchor-id="the-accuracy-is">The accuracy is:</h4>
<div class="cell" data-execution_count="393">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>(y_hat_tests <span class="op">==</span> y_test)[group_test <span class="op">==</span> <span class="dv">1</span>].mean()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="393">
<pre><code>0.7819096468731506</code></pre>
</div>
</div>
</section>
<section id="the-models-positive-predictive-value-ppv-is" class="level4">
<h4 class="anchored" data-anchor-id="the-models-positive-predictive-value-ppv-is">The model’s positive predictive value (PPV) is:</h4>
<div class="cell" data-execution_count="394">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>bias_rates(confusion_matrix(y_test[group_test <span class="op">==</span> <span class="dv">1</span>], y_hat_tests[group_test <span class="op">==</span> <span class="dv">1</span>]), <span class="st">"PPV"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0.7822506861848124</code></pre>
</div>
</div>
</section>
<section id="the-models-false-negative-rate-fnr-is" class="level4">
<h4 class="anchored" data-anchor-id="the-models-false-negative-rate-fnr-is">The model’s false negative rate FNR is:</h4>
<div class="cell" data-execution_count="395">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>bias_rates(confusion_matrix(y_test[group_test <span class="op">==</span> <span class="dv">1</span>], y_hat_tests[group_test <span class="op">==</span> <span class="dv">1</span>]), <span class="st">"FNR"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0.3685376661742984</code></pre>
</div>
</div>
</section>
<section id="the-models-false-positive-rate-fpr-is" class="level4">
<h4 class="anchored" data-anchor-id="the-models-false-positive-rate-fpr-is">The model’s false positive rate FPR is:</h4>
<div class="cell" data-execution_count="396">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>bias_rates(confusion_matrix(y_test[group_test <span class="op">==</span> <span class="dv">1</span>], y_hat_tests[group_test <span class="op">==</span> <span class="dv">1</span>]), <span class="st">"FPR"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0.1175115207373272</code></pre>
</div>
</div>
</section>
</section>
<section id="for-female-individuals" class="level3">
<h3 class="anchored" data-anchor-id="for-female-individuals">For Female Individuals</h3>
<section id="the-accuracy-for-female-individuals-is" class="level4">
<h4 class="anchored" data-anchor-id="the-accuracy-for-female-individuals-is">The accuracy for female individuals is:</h4>
<div class="cell" data-execution_count="397">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>(y_hat_tests <span class="op">==</span> y_test)[group_test <span class="op">==</span> <span class="dv">2</span>].mean()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="397">
<pre><code>0.8236757541204519</code></pre>
</div>
</div>
</section>
<section id="the-models-positive-predictive-value-ppv-is-1" class="level4">
<h4 class="anchored" data-anchor-id="the-models-positive-predictive-value-ppv-is-1">The model’s positive predictive value (PPV) is:</h4>
<div class="cell" data-execution_count="398">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>bias_rates(confusion_matrix(y_test[group_test <span class="op">==</span> <span class="dv">2</span>], y_hat_tests[group_test <span class="op">==</span> <span class="dv">2</span>]), <span class="st">"PPV"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0.6761737604212373</code></pre>
</div>
</div>
</section>
<section id="the-models-false-negative-rate-fnr-is-1" class="level4">
<h4 class="anchored" data-anchor-id="the-models-false-negative-rate-fnr-is-1">The model’s false negative rate FNR is:</h4>
<div class="cell" data-execution_count="399">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>bias_rates(confusion_matrix(y_test[group_test <span class="op">==</span> <span class="dv">2</span>], y_hat_tests[group_test <span class="op">==</span> <span class="dv">2</span>]), <span class="st">"FNR"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0.3845846645367412</code></pre>
</div>
</div>
</section>
<section id="the-models-false-positive-rate-fpr-is-1" class="level4">
<h4 class="anchored" data-anchor-id="the-models-false-positive-rate-fpr-is-1">The model’s false positive rate FPR is:</h4>
<div class="cell" data-execution_count="400">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>bias_rates(confusion_matrix(y_test[group_test <span class="op">==</span> <span class="dv">2</span>], y_hat_tests[group_test <span class="op">==</span> <span class="dv">2</span>]), <span class="st">"FPR"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0.10331793364132717</code></pre>
</div>
</div>
<p>For our binary sex-based income classification task, our overall measures tell us:</p>
<ul>
<li>The model has a slightly higher accuracy for females than for males (about a 4% difference)
<ul>
<li>Accuracy is the # of correct predictions / # of total predictions</li>
<li>Basically, the likelihood that the model’s prediction matches the actual label.</li>
</ul></li>
<li>The model’s PPV is significantly higher for males than for females (about a 10 % difference), meaning that when the model predicts that males make &gt;\$50k, it is right 10% more often than when it predicts that females make &gt;\$50k.
<ul>
<li>PPV is the likelihood that for a given positive prediction, the corresponding actual label that was also positive.</li>
</ul></li>
<li>The model has very similar FNR and FPR rates for both groups, meaning that the rate at which the model fail to identify individuals making &gt;\$50k and &lt;\$50k is almost the same for both groups.
<ul>
<li>FNR is the the likelihood that for a given actual label that is a positive, the model incorectly predicts a negative label. Basically, failure to identify positive cases.</li>
<li>FPR is the the likelihood that for a given actual label that is a negative, the model incorectly predicts a positive label. Basically, failure to identify negative cases.</li>
</ul></li>
</ul>
<p>Note: “Positive” and “negative” are not indicative good or bad. In this context, “positive” means making &gt;$50k, “negative” means making &lt;\$50k.</p>
</section>
</section>
</section>
<section id="bias-measures" class="level2">
<h2 class="anchored" data-anchor-id="bias-measures">Bias Measures</h2>
<section id="calibration" class="level3">
<h3 class="anchored" data-anchor-id="calibration">Calibration</h3>
<p>As defined by Chouldechova in <a href="https://via.hypothes.is/https://arxiv.org/pdf/1703.00056.pdf">this paper</a>, “a score S = S(x) is said to be well-calibrated if it reflects the same likelihood of recidivism irrespective of the individuals’ group membership.”</p>
<p>In our context, when we are doing binary classification for sex-based income, the calibration takes on the form of the PPV. Namely, our model would be well-calibrated if the fraction of predicted individuals making &gt;\$50k who actually make &gt;\$50k is the same across groups.</p>
<div class="cell" data-execution_count="456">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>df2 <span class="op">=</span> pd.DataFrame(X_test, columns <span class="op">=</span> features_to_use) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="457">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>df2[<span class="st">"group"</span>] <span class="op">=</span> group_test</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>df2[<span class="st">"label"</span>] <span class="op">=</span> y_test </span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>df2[<span class="st">"predicted_label"</span>] <span class="op">=</span> y_hat_tests</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="458">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>df2_calibration <span class="op">=</span> df2.query(<span class="st">"predicted_label == True"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="459">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>df2_calibration <span class="op">=</span> df2_calibration.groupby([<span class="st">"group"</span>, <span class="st">"predicted_label"</span>])[<span class="st">"label"</span>].mean().reset_index(name <span class="op">=</span> <span class="st">"mean"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="460">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>sns.set_theme(style<span class="op">=</span><span class="st">"whitegrid"</span>)</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>p <span class="op">=</span> sns.catplot(data <span class="op">=</span> df2_calibration, kind <span class="op">=</span> <span class="st">"bar"</span>, x <span class="op">=</span> <span class="st">"predicted_label"</span>, y <span class="op">=</span> <span class="st">"mean"</span>, hue <span class="op">=</span> <span class="st">"group"</span>, legend_out <span class="op">=</span> <span class="va">False</span>)</span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>new_labels <span class="op">=</span> [<span class="st">'Male'</span>, <span class="st">'Female'</span>]</span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> t, l <span class="kw">in</span> <span class="bu">zip</span>(p._legend.texts, new_labels):</span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a>    t.set_text(l)</span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-8"><a href="#cb57-8" aria-hidden="true" tabindex="-1"></a>sns.move_legend(p, <span class="st">"upper right"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-40-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>Of those who were predicted to make &gt;\$50k, more males actually make &gt;\$50k.</p>
</section>
<section id="error-rate-balance" class="level3">
<h3 class="anchored" data-anchor-id="error-rate-balance">Error Rate Balance</h3>
<p>A prediction satisfies error rate balance if the FPR and FNR are equal across groups.</p>
<div class="cell" data-execution_count="467">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>fig, axarr <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">3</span>, figsize<span class="op">=</span>(<span class="dv">15</span>,<span class="fl">3.2</span>), sharex <span class="op">=</span> <span class="va">False</span>, sharey <span class="op">=</span> <span class="va">False</span>)</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a><span class="co">#overall</span></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>cm1 <span class="op">=</span> confusion_matrix(y_test, y_hat_tests, labels<span class="op">=</span>model.classes_, normalize <span class="op">=</span> <span class="st">"true"</span>)</span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>disp1 <span class="op">=</span> ConfusionMatrixDisplay(confusion_matrix<span class="op">=</span>cm1,</span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a>                              display_labels<span class="op">=</span>model.classes_)</span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-8"><a href="#cb58-8" aria-hidden="true" tabindex="-1"></a><span class="co">#male</span></span>
<span id="cb58-9"><a href="#cb58-9" aria-hidden="true" tabindex="-1"></a>cm2 <span class="op">=</span> confusion_matrix(y_test[group_test <span class="op">==</span> <span class="dv">1</span>], y_hat_tests[group_test <span class="op">==</span> <span class="dv">1</span>], labels<span class="op">=</span>model.classes_)</span>
<span id="cb58-10"><a href="#cb58-10" aria-hidden="true" tabindex="-1"></a>disp2 <span class="op">=</span> ConfusionMatrixDisplay(confusion_matrix<span class="op">=</span>cm2,</span>
<span id="cb58-11"><a href="#cb58-11" aria-hidden="true" tabindex="-1"></a>                              display_labels<span class="op">=</span>model.classes_)</span>
<span id="cb58-12"><a href="#cb58-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-13"><a href="#cb58-13" aria-hidden="true" tabindex="-1"></a><span class="co">#female</span></span>
<span id="cb58-14"><a href="#cb58-14" aria-hidden="true" tabindex="-1"></a>cm3 <span class="op">=</span> confusion_matrix(y_test[group_test <span class="op">==</span> <span class="dv">2</span>], y_hat_tests[group_test <span class="op">==</span> <span class="dv">2</span>], labels<span class="op">=</span>model.classes_)</span>
<span id="cb58-15"><a href="#cb58-15" aria-hidden="true" tabindex="-1"></a>disp3 <span class="op">=</span> ConfusionMatrixDisplay(confusion_matrix<span class="op">=</span>cm3,</span>
<span id="cb58-16"><a href="#cb58-16" aria-hidden="true" tabindex="-1"></a>                              display_labels<span class="op">=</span>model.classes_)</span>
<span id="cb58-17"><a href="#cb58-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-18"><a href="#cb58-18" aria-hidden="true" tabindex="-1"></a>disp1.plot(ax<span class="op">=</span>axarr[<span class="dv">0</span>], cmap <span class="op">=</span> plt.cm.Blues)</span>
<span id="cb58-19"><a href="#cb58-19" aria-hidden="true" tabindex="-1"></a>axarr[<span class="dv">0</span>].grid(visible<span class="op">=</span><span class="va">None</span>)</span>
<span id="cb58-20"><a href="#cb58-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-21"><a href="#cb58-21" aria-hidden="true" tabindex="-1"></a>disp2.plot(ax<span class="op">=</span>axarr[<span class="dv">1</span>], cmap <span class="op">=</span> plt.cm.Blues)</span>
<span id="cb58-22"><a href="#cb58-22" aria-hidden="true" tabindex="-1"></a>axarr[<span class="dv">1</span>].grid(visible<span class="op">=</span><span class="va">None</span>)</span>
<span id="cb58-23"><a href="#cb58-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-24"><a href="#cb58-24" aria-hidden="true" tabindex="-1"></a>disp3.plot(ax<span class="op">=</span>axarr[<span class="dv">2</span>], cmap <span class="op">=</span> plt.cm.Blues)</span>
<span id="cb58-25"><a href="#cb58-25" aria-hidden="true" tabindex="-1"></a>axarr[<span class="dv">2</span>].grid(visible<span class="op">=</span><span class="va">None</span>)</span>
<span id="cb58-26"><a href="#cb58-26" aria-hidden="true" tabindex="-1"></a></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-41-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>As observed in the overall measures section, the FPR and FNR are nearly the same across groups.</p>
</section>
<section id="statistical-parity" class="level3">
<h3 class="anchored" data-anchor-id="statistical-parity">Statistical Parity</h3>
<p>A prediction satisfies statistical parity if the likelihood of getting a certain prediction is the same across groups.</p>
<p>Very subjective picking what the worse classification is. In hands of gov. for taxes, maybe it’s worse to be predicted high, cuz you’ll pay more taxes and good for lower cuz you’ll get more benefits. Bad for people trying to charge you (loans maybe idk), cuz they’ll predict you have more money and charge you more.</p>
<div class="cell" data-execution_count="490">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>df2_stat_parity_v <span class="op">=</span> df2.groupby([<span class="st">"group"</span>], as_index<span class="op">=</span><span class="va">False</span>)[<span class="st">"predicted_label"</span>].value_counts(normalize <span class="op">=</span> <span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="491">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>df2_stat_parity_v</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="491">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>group</th>
      <th>predicted_label</th>
      <th>proportion</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
      <td>False</td>
      <td>0.676563</td>
    </tr>
    <tr>
      <th>1</th>
      <td>1</td>
      <td>True</td>
      <td>0.323437</td>
    </tr>
    <tr>
      <th>2</th>
      <td>2</td>
      <td>False</td>
      <td>0.763761</td>
    </tr>
    <tr>
      <th>3</th>
      <td>2</td>
      <td>True</td>
      <td>0.236239</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<div class="cell" data-execution_count="492">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>sns.set_theme(style<span class="op">=</span><span class="st">"whitegrid"</span>)</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>p <span class="op">=</span> sns.catplot(data <span class="op">=</span> df2_stat_parity_v, kind <span class="op">=</span> <span class="st">"bar"</span>, x <span class="op">=</span> <span class="st">"predicted_label"</span>, y <span class="op">=</span> <span class="st">"proportion"</span>, hue <span class="op">=</span> <span class="st">"group"</span>, legend_out <span class="op">=</span> <span class="va">False</span>)</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>new_labels <span class="op">=</span> [<span class="st">'Male'</span>, <span class="st">'Female'</span>]</span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> t, l <span class="kw">in</span> <span class="bu">zip</span>(p._legend.texts, new_labels):</span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a>    t.set_text(l)</span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-8"><a href="#cb61-8" aria-hidden="true" tabindex="-1"></a>sns.move_legend(p, <span class="st">"upper right"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-44-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>The model is more likely to predict that males make &gt;50k and that females make &lt;\$50k.</p>
</section>
</section>
</section>
<section id="concluding-discussion" class="level1">
<h1>Concluding Discussion</h1>
<section id="what-groups-of-people-could-stand-to-benefit-from-a-system-that-is-able-to-predict-income-levels" class="level5">
<h5 class="anchored" data-anchor-id="what-groups-of-people-could-stand-to-benefit-from-a-system-that-is-able-to-predict-income-levels">What groups of people could stand to benefit from a system that is able to predict income levels?</h5>
<blockquote class="blockquote">
<p>Many groups could benefit immalesely from a ML model that accurately predicts someone’s income being above a certain threshold. Companies that loan money like banks and car dealerships could use this for expedited decisions on loan eligibility, amounts, and interest rates. By this same logic, this model could also help make social welfare programs more efficient. For individuals that change jobs or achieve a higher education level (amongst other features), this model may be helpful in predicting their new income.</p>
</blockquote>
</section>
<section id="based-on-your-bias-audit-do-you-feel-that-your-model-displays-problematic-bias" class="level5">
<h5 class="anchored" data-anchor-id="based-on-your-bias-audit-do-you-feel-that-your-model-displays-problematic-bias">Based on your bias audit, do you feel that your model displays problematic bias?</h5>
<section id="ppv-fpr-fnr-relationship" class="level6">
<h6 class="anchored" data-anchor-id="ppv-fpr-fnr-relationship">PPV, FPR, FNR Relationship:</h6>
<p><span class="math display">\[\begin{equation}
FPR = \frac{p}{1-p}\frac{1-PPV}{PPV}(1-FNR)
\end{equation}\]</span></p>
<blockquote class="blockquote">
<p>As can be deduced from this equation, if the prevalence (base rates) is different across groups, it is mathematically impossible for the PPV to be equal and error rates to be balanced across groups.</p>
</blockquote>
<blockquote class="blockquote">
<p>Our model is not well-calibrated (unequal PPVs for males and females), but it does satisfy error-rate balance thanks to its PPV disparity.</p>
</blockquote>
<blockquote class="blockquote">
<p>For this , calibration is PPV. So higher PPV for male means that the likelihood that when we predict positively, the actual is positive is higher for male. From the female perspective, having a lower PPV means that there is a decreased likelihood that when we predict positively, the actual is positive for females.</p>
</blockquote>
<blockquote class="blockquote">
<p>Thus, more females will get “undeserving” positive predictions (false positives: predict positive, actual is negative).</p>
</blockquote>
<blockquote class="blockquote">
<p>FPR is unaffected though, because of the two group’s differing prevalence (base rates). Since there are a lot more true negatives for females, FPR balances out. FPR = FP / FP + TN</p>
</blockquote>
<blockquote class="blockquote">
<p>In spite of our balanced error-rate, our model is still more likely to predict males make &gt;50k (statistical parity discrepancy). Depending on our model’s use case, this may be a form of allocative bias as it could have a disparate impact on either group.</p>
</blockquote>
</section>
</section>
<section id="based-on-your-bias-audit-what-could-be-the-impact-of-deploying-your-model-for-large-scale-prediction-in-commercial-or-governmaletal-settings" class="level5">
<h5 class="anchored" data-anchor-id="based-on-your-bias-audit-what-could-be-the-impact-of-deploying-your-model-for-large-scale-prediction-in-commercial-or-governmaletal-settings">Based on your bias audit, what could be the impact of deploying your model for large-scale prediction in commercial or governmaletal settings?</h5>
<blockquote class="blockquote">
<p>In commercial settings if our model is used for loan-related tasks, it will probably be for the benefit of the individual that the model predicts that they make &gt;50k as it will help them get approved. In this scenario a disproportionate false negative rate is bad because it will mean that a certain group is less likely to get favorable loans because the model failed to identify positive cases at a higher rate for this group.</p>
</blockquote>
<blockquote class="blockquote">
<p>In gov. settings if our model is used for distribution of welfare tasks, it will be for the benefit of the individual that the model predicts that they make &lt;50k. In this scenario a disproportionate false positive rate is bad because it will mean that a certain group is less likely to get favorable loans because the model failed to identify negative cases at a higher rate for this group.</p>
</blockquote>
<blockquote class="blockquote">
<p>Since our error rates are balanced, the model will not lead to disparate impact in either scenario, so it could be deployed for both simultaneously.</p>
</blockquote>
<blockquote class="blockquote">
<p>Nonetheless, becasuse of the statistical parity violation, a higher proportion of males are more likely to attain favorable loans, while a higher proportion of females are more likely to receive favorable welfare benefits.</p>
</blockquote>
<blockquote class="blockquote">
<p>Fairness intervention tactics to balance out the statistical parity violation may be employed if deemed fit.</p>
</blockquote>
</section>
<section id="beyond-bias-are-there-other-potential-problems-associated-with-deploying-your-model-that-make-you-uncomfortable-how-would-you-propose-addressing-some-of-these-problems" class="level5">
<h5 class="anchored" data-anchor-id="beyond-bias-are-there-other-potential-problems-associated-with-deploying-your-model-that-make-you-uncomfortable-how-would-you-propose-addressing-some-of-these-problems">Beyond bias, are there other potential problems associated with deploying your model that make you uncomfortable? How would you propose addressing some of these problems?</h5>
<blockquote class="blockquote">
<p>As specified in <a href="https://arxiv.org/pdf/2108.04884.pdf">the paper</a> that developed the ACS Income prediction task, there are glaring limitations to deploying this model for more general use:</p>
</blockquote>
<blockquote class="blockquote">
<p>The data is U.S centric (page 8). To deploy this model for other countries, it would be important to ensure that demographic tends regarding sex-based income are similar in those countries. Preferably, data from those countries would be collected and use to train a different model that does the same prediction task.</p>
</blockquote>
<blockquote class="blockquote">
<p>“Training and testing on different states leads to unpredictable results” (page 10). To address this, we should stick to training and testing on the same state.</p>
</blockquote>
<blockquote class="blockquote">
<p>“Fairness criteria are more stable over time than predictive accuracy” (page 10). To address this, we could add econonomic metrics like inflation to make time-sensitive modeling more accurate. The consistency in fairness criteria over time could likely be attributed to base rates remaining stagnant, which may be indiciative of our society’s lack of social progress to close the gender pay gap.</p>
</blockquote>
</section>
<section id="note-it-is-important-to-acknowdledge-the-issues-feeding-bias-into-our-model-at-their-core.-as-exemplified-by-our-base-rates-males-income-is-higher-than-females.-things-like-equal-access-to-education-and-industry-wide-initiaves-to-help-women-advance-in-the-workplace-may-help-close-the-gap." class="level3">
<h3 class="anchored" data-anchor-id="note-it-is-important-to-acknowdledge-the-issues-feeding-bias-into-our-model-at-their-core.-as-exemplified-by-our-base-rates-males-income-is-higher-than-females.-things-like-equal-access-to-education-and-industry-wide-initiaves-to-help-women-advance-in-the-workplace-may-help-close-the-gap.">NOTE: It is important to acknowdledge the issues feeding bias into our model at their core. As exemplified by our base rates, males’ income is higher than females’. Things like equal access to education and industry-wide initiaves to help women advance in the workplace may help close the gap.</h3>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>